project_id = "jzkzqpeorsehwvwcyjkf"

[api]
enabled = true
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
# Port configs removed; CLI now assigns automatically

[studio]
enabled = true

[inbucket]
enabled = true

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://jzkzqpeorsehwvwcyjkf.supabase.co"]
jwt_expiry = 3600
enable_manual_linking = false

# Removed [rest] → no longer supported

[realtime]
enabled = true

[edge_runtime]
enabled = true

[analytics]
enabled = false

# Functions configs (kept as-is)
[functions.send-contact-email]
verify_jwt = false

[functions.send-signup-confirmation]
verify_jwt = false

[functions.submit-assignment-request]
verify_jwt = true

[functions.submit-book-order]
verify_jwt = true

[functions.submit-book-request]
verify_jwt = true

[functions.submit-buyback-request]
verify_jwt = true

[functions.submit-campus-tour-booking]
verify_jwt = true

[functions.submit-carton-booking]
verify_jwt = true

[functions.submit-celebration-booking]
verify_jwt = true

[functions.submit-book-listing]
verify_jwt = true

[functions.get-semester-books]
verify_jwt = false

[functions.submit-book-selection]
verify_jwt = true

[functions.validate-kiit-email]
verify_jwt = true

[functions.create-resale-order]
verify_jwt = true

[functions.verify-resale-payment]
verify_jwt = true

[functions.confirm-resale-delivery]
verify_jwt = true

[functions.moderate-resale-listing]
verify_jwt = false
